#!/bin/zsh

java -Xdock:icon="./icon.png" -Dfile.encoding=utf8 -Dcom.apple.mrj.application.growbox.intrudes=false -Dcom.apple.mrj.application.live-resize=true -Dcom.apple.macos.smallTabs=true -Xdock:name=Amp -Dmarathon.useAppleMenuBar=true --module-path ./javafx/lib --add-modules=javafx.controls,javafx.fxml -jar ./app.jar